CRAFT_ITEMS: dict[str, dict[int, list]] = {
    "cooking": {
        0: ["cooked_gudgeon", ],
        5: ["cooked_gudgeon", ],
        10: ["cooked_shrimp", "cheese", "beef_stew", "mushroom_soup", "fried_eggs", ],
        15: ["cooked_shrimp", "cooked_wolf_meat", "fried_eggs", ],
        20: ["cooked_trout", "cheese", "cooked_wolf_meat", ],
        25: ["cooked_trout", "cheese", "cooked_wolf_meat", ],
        30: ["cooked_trout", "mushroom_soup", "beef_stew", ],
        35: ["cooked_trout", "mushroom_soup", "beef_stew", ],
        40: ["cooked_salmon", "mushroom_soup", "beef_stew", "cheese", "cooked_wolf_meat", ],
    },
    "weaponcrafting": {
        0: ["copper_dagger", ],
        5: ["sticky_sword", "sticky_dagger", "fire_staff", "water_bow", ],
        10: ["iron_pickaxe", "iron_axe", "spruce_fishing_rod",
             "iron_sword", "iron_dagger", "fire_bow", "greater_wooden_staff",
             "iron_sword", "iron_dagger", "fire_bow", "greater_wooden_staff",
             "iron_sword", "iron_dagger", "fire_bow", "greater_wooden_staff",
             "iron_pickaxe", "iron_axe", "spruce_fishing_rod", ],
        15: ["iron_sword", "iron_sword", "iron_sword", "iron_sword", "iron_sword",
            # "mushstaff", "mushmush_bow", "multislimes_sword"
             ],
        20: ["battlestaff", "steel_battleaxe", "battlestaff", "skull_staff", ],
        25: ["battlestaff", "steel_battleaxe", "battlestaff", "skull_staff",
             # "dreadful_staff", "skull_wand",
             ],
        30: ["death_knight_sword", "gold_sword", "greater_dreadful_staff", ],
        35: ["magic_bow", "cursed_specter", "gold_sword", "greater_dreadful_staff", "strangold_sword", ],
        40: ["sanguine_edge_of_rosen", ],
    },
    "gearcrafting": {
        0: ["wooden_shield", "copper_helmet", "copper_helmet", "wooden_shield", "copper_boots", ],
        5: ["copper_armor", "copper_legs_armor", "feather_coat", "feather_coat", ],
        10: ["slime_shield", "iron_helm", "iron_armor", "iron_legs_armor", "adventurer_pants", "leather_hat",
             "iron_boots", "adventurer_vest", ],
        15: ["adventurer_boots", "adventurer_boots", "adventurer_boots", "adventurer_boots", "adventurer_boots",
             "adventurer_boots", "adventurer_boots", "adventurer_boots", "adventurer_boots", "adventurer_boots",
             # "mushmush_wizard_hat", "lucky_wizard_hat",
             ],
        20: ["steel_shield", "steel_helm", "steel_boots", "steel_armor", "steel_legs_armor",
             "tromatising_mask", "magic_wizard_hat", "serpent_skin_legs_armor",
             "skeleton_pants", "skeleton_helmet", "skeleton_armor", ],
        25: ["bandit_armor", "lizard_skin_legs_armor", "lizard_skin_armor", "piggy_pants"],
        30: ["gold_mask", "gold_helm", "gold_platelegs", "gold_platebody",
             "gold_mask", "gold_helm", "gold_platelegs", "gold_platebody",
             "gold_boots", "lizard_boots", "gold_shield", "obsidian_helmet", "obsidian_legs_armor", ],
        35: ["lich_crown", "strangold_armor", "strangold_legs_armor", "strangold_helmet",
             "cursed_hat", "malefic_armor", "ancient_jean", "obsidian_armor", ],
        40: ["batwing_helmet", "fire_shield", "water_shield", "air_shield", "earth_shield", ],
    },
    "jewelrycrafting": {
        0: ["copper_ring"],
        5: ["life_amulet"],
        10: ["iron_ring", "air_and_water_amulet", "fire_and_earth_amulet"],
        15: ["life_ring", "air_ring", "earth_ring", "fire_ring", "water_ring"],
        20: ["steel_ring", "steel_ring", "steel_ring", "steel_ring", "steel_ring",
             "dreadful_amulet", "skull_amulet", "dreadful_amulet", "skull_amulet", "dreadful_ring", "skull_ring"],
        25: ["steel_ring", "skull_amulet", "dreadful_amulet",
             # "ruby_amulet", "topaz_amulet", "sapphire_amulet", "emerald_amulet"
             ],
        30: ["gold_ring", "gold_ring", "gold_ring", "gold_ring", "gold_ring",
             # "ruby_ring", "topaz_ring", "sapphire_ring", "emerald_ring"
             ],
        35: ["gold_ring", "diamond_amulet", "magic_stone_amulet", "greater_dreadful_amulet"],
        40: ["gold_ring", "diamond_amulet", "magic_stone_amulet", "greater_dreadful_amulet"],
    },
    "mining": {
        0: ["copper"],
        5: ["copper"],
        10: ["iron"],
        15: ["iron"],
        20: ["iron", "iron", "steel"],
        25: ["iron", "iron", "steel"],
        30: ["gold"],
        35: ["strangold", "steel", "gold_ore"],
        40: ["strangold", "steel", "gold_ore"],
    },
    "woodcutting": {
        0: ["ash_plank"],
        5: ["ash_plank"],
        10: ["spruce_plank", ],
        15: ["spruce_plank", ],
        20: ["hardwood_plank", ],
        25: ["hardwood_plank", ],
        30: ["dead_wood_plank", ],
        35: ["magical_plank", "dead_wood_plank", "magical_plank", "hardwood_plank", ],
        40: ["magical_plank", "dead_wood_plank", "magical_plank", "hardwood_plank", ],
    },
}
ROLES = {
    "Lert": ("weaponcrafting", "gearcrafting"),
    "Ralernan": ("jewelrycrafting", "trader"),
    "Kerry": ("mining", "mining"),
    "Karven": ("woodcutting", "woodcutting"),
    "Warrant": ("cooking", "cooking")}
ELEMENTS = ["fire", "earth", "water", "air"]
SLOT_TYPES: dict[str, str] = {
    "weapon_slot": "weapon",
    "shield_slot": "shield",
    "helmet_slot": "helmet",
    "body_armor_slot": "body_armor",
    "leg_armor_slot": "leg_armor",
    "boots_slot": "boots",
    "ring1_slot": "ring",
    "ring2_slot": "ring",
    "amulet_slot": "amulet",
    "artifact1_slot": "artifact",
    "artifact2_slot": "artifact",
    "artifact3_slot": "artifact",
    "consumable1_slot": "consumable",
    "consumable2_slot": "consumable",
}
CRAFTABLE = ["weapon", "shield", "helmet", "body_armor", "leg_armor", "boots", "amulet", "ring"]
COORDINATES: dict[str, tuple] = {
    "copper_ore": "copper",
    "iron_ore": "iron",
    "coal": "coal",
    "gold_ore": "gold",
    "strange_ore": "strange",
    "ash_wood": "ash",
    "spruce_wood": "spruce",
    "birch_wood": "birch",
    "dead_wood": "dead",
    "magic_wood": "magic",
    "gudgeon": "gudgeon",
    "shrimp": "shrimp",
    "trout": "trout",
    "bass": "bass",
}
