ELEMENTS = ["fire", "earth", "water", "air"]
CRAFT_ITEMS: dict[str, dict[int, list]] = {
    "cooking": {
        0: ["cooked_gudgeon"],
        5: ["cooked_gudgeon"],
        10: ["cooked_shrimp", "beef_stew", "mushroom_soup", "fried_eggs"],
        15: ["cooked_shrimp", "cooked_wolf_meat", "fried_eggs"],
        20: ["cooked_trout", "cheese", "cooked_wolf_meat"],
        25: ["cooked_trout", "cooked_wolf_meat", "cheese"],
        30: ["cooked_trout", "mushroom_soup", "beef_stew"],
        35: ["cooked_trout", "mushroom_soup", "beef_stew"],
    },
    "weaponcrafting": {
        0: ["copper_dagger"],
        5: ["sticky_sword", "sticky_dagger", "fire_staff", "water_bow"],
        10: ["iron_sword", "iron_dagger", "fire_bow", "greater_wooden_staff"],
        15: ["mushstaff", "mushmush_bow", "multislimes_sword"],
        20: ["battlestaff", "steel_axe", "battlestaff", "steel_axe",
             "battlestaff", "steel_axe", "skull_staff", "forest_whip", ],
        25: ["skull_wand", "dreadful_staff"],
        30: ["gold_sword", "greater_dreadful_staff"],
        35: ["gold_sword", "greater_dreadful_staff"],
    },
    "gearcrafting": {
        0: ["wooden_shield", "copper_helmet", "copper_helmet", "wooden_shield", "copper_boots"],
        5: ["copper_armor", "copper_legs_armor", "feather_coat", "feather_coat"],
        10: ["slime_shield", "leather_hat", "iron_boots", "iron_helm", "iron_armor", "iron_legs_armor", "adventurer_pants", "adventurer_vest"],
        15: ["adventurer_boots", "mushmush_wizard_hat", "lucky_wizard_hat"],
        20: ["magic_wizard_hat", "steel_shield", "steel_helm", "steel_boots", "steel_armor", "steel_legs_armor"
                                                                                             "tromatising_mask",
             "skeleton_pants", "skeleton_helmet", "skeleton_armor", "serpent_skin_legs_armor"],
        25: ["lizard_skin_legs_armor", "lizard_skin_armor", "piggy_pants"],
        30: ["gold_mask", "gold_helm", "steel_boots", "steel_armor"],
        35: ["gold_mask", "gold_helm", "steel_boots", "steel_armor"],
    },
    "jewelrycrafting": {
        0: ["copper_ring"],
        5: ["life_amulet"],
        10: ["iron_ring", "air_and_water_amulet", "fire_and_earth_amulet"],
        15: ["life_ring", "air_ring", "earth_ring", "fire_ring", "water_ring"],
        20: ["steel_ring", "ring_of_chance", "dreadful_ring", "skull_ring", ],
        25: ["gold_ring", "topaz_ring", "sapphire_ring", "emerald_ring"],
        30: ["gold_ring", "topaz_ring", "sapphire_ring", "emerald_ring"],
        35: ["gold_ring", "topaz_ring", "sapphire_ring", "emerald_ring"],
    },
    "mining": {
        0: ["copper"],
        5: ["copper"],
        10: ["iron"],
        15: ["iron"],
        20: ["steel"],
        25: ["steel"],
        30: ["gold"],
        35: ["strange_ore"],
    },
    "woodcutting": {
        0: ["ash_plank"],
        5: ["ash_plank"],
        10: ["spruce_plank"],
        15: ["spruce_plank"],
        20: ["hardwood_plank"],
        25: ["hardwood_plank"],
        30: ["dead_wood_plank"],
        35: ["magical_plank"],
    },
}
SLOT_TYPES: dict[str, str] = {
    "weapon_slot": "weapon",
    "shield_slot": "shield",
    "helmet_slot": "helmet",
    "body_armor_slot": "body_armor",
    "leg_armor_slot": "leg_armor",
    "boots_slot": "boots",
    "ring1_slot": "ring",
    "ring2_slot": "ring",
    "amulet_slot": "amulet",
    "artifact1_slot": "artifact",
    "artifact2_slot": "artifact",
    "artifact3_slot": "artifact",
    "consumable1_slot": "consumable",
    "consumable2_slot": "consumable",
}
CRAFTABLE = ["weapon", "shield", "helmet", "body_armor", "leg_armor", "boots", "amulet", "ring"]
COORDINATES: dict[str, tuple] = {
    "copper_ore": (2, 0),
    "iron_ore": (1, 7),
    "coal": (1, 6),
    "gold_ore": (10, -4),
    "ash_wood": (-1, 0),
    "spruce_wood": (2, 6),
    "birch_wood": (3, 5),
    "dead_wood": (9, 8),
    "gudgeon": (4, 2),
    "shrimp": (5, 2),
    "trout": (7, 12),
    "bass": (6, 12),

    "cooking": (1, 1),
    "mining": (1, 5),
    "weaponcrafting": (2, 1),
    "gearcrafting": (3, 1),
    "woodcutting": (-2, -3),
    "jewelrycrafting": (1, 3),
}
